title: M365 Bits
description: M365 Bits
theme: just-the-docs
color_scheme: dark

url: https://d.stevewb.net

back_to_top: true
back_to_top_text: "Back to top"

defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/
  - spec/
  - tmp
  - .rspec
  
# For copy button on code
enable_copy_code_button: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

